export const courses = [
  {
    id: 1,
    title: "Advanced Calculus II",
    category: "MATHEMATICS",
    exam: "STEM Entrance",
    subject: "Mathematics",
    image: "/courses/math.jpg",
    price: "Free",
  },
  {
    id: 2,
    title: "Organic Chemistry Principles",
    category: "SCIENCE",
    exam: "Medical Prep",
    subject: "Chemistry",
    image: "/courses/science.jpg",
    price: "Premium",
  },
  {
    id: 3,
    title: "Modern European History",
    category: "HUMANITIES",
    exam: "General Arts",
    subject: "History",
    image: "/courses/humanities.jpg",
    price: "Free",
  },
  {
    id: 4,
    title: "Full-Stack Development",
    category: "TECHNOLOGY",
    exam: "Computer Science",
    subject: "Programming",
    image: "/courses/technology.jpg",
    price: "Premium",
  },
  {
    id: 5,
    title: "Molecular Biology",
    category: "SCIENCE",
    exam: "Medical Prep",
    subject: "Biology",
    image: "/courses/biology.jpg",
    price: "Free",
  },
  {
    id: 6,
    title: "Data Science with Python",
    category: "TECHNOLOGY",
    exam: "STEM Entrance",
    subject: "Data Science",
    image: "/courses/technology.jpg",
    price: "Premium",
  },
];
